### ISSUE TITLE
UnicodeEncodeError: in Windows

### ISSUE THREAD

**Issue by SlimJimPoisson** [kmac/mlbv#18]
I assume that I am one of the few trying to get this to work under Windows (10). After resolving the "os.environ['HOME'] not supported on Windows" issue this is the latest error message that I am receiving.

UnicodeEncodeError: 'gbk' codec can't encode character '\xf1' in position 41310: illegal multibyte sequence

I am amazed by your quick response times to issues during your "vacation", but then what's more fun than coding?

**Comment by tonywagner** [comment]
What command did you run? Is that the whole output? I ran this on Win10 and didn't encounter this.

**Comment by SlimJimPoisson** [comment]
Sorry, it's not the whole output. I will include the traceback log here. I had originally invoked it with no parameters, but just now I tried a number of different commands and always received the exact same message (though the position changes). The only command that did not cause this error was "--init" which informed me that the config file already exists.

Entire output:
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\mlbv.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\mlbam\mlbv.py", line 194, in main
    game_day_tuple_list = gamedata_parser.process_game_data(args.date, args.days)
  File "c:\program files\python37\lib\site-packages\mlbam\gamedata.py", line 263, in process_game_data
    game_records = self._get_games_by_date(game_date)
  File "c:\program files\python37\lib\site-packages\mlbam\gamedata.py", line 119, in _get_games_by_date
    json_data = util.request_json(url, 'gamedata')
  File "c:\program files\python37\lib\site-packages\mlbam\util.py", line 92, in request_json
    out.write(response.text)
UnicodeEncodeError: 'gbk' codec can't encode character '\xf1' in position 41310: illegal multibyte sequence

**Comment by kmac** [comment]
Looks like it's a gbk encoding issue. My system default encoding is utf-8, yours must be gbk. Which shouldn't matter but it must be a bug somewhere with regards to the unicode handling. It's not exactly my strong point... If you want to temporarily bypass this exact error (and you may run into more further down - I suspect you're blazing a new trail here - then you can try manually editing the config.py file and changing line 19:

````
SAVE_JSON_FILE = True
````
to `False`. That will bypass this particular code and you can see how far it gets past that.

**Comment by tonywagner** [comment]
Oh wait -- I did see something like this before! The Windows command prompt can't handle that encoding.

Yes, the fix was to disable SAVE_JSON_FILE as kmac describes.

Could False just be the default value for that? Or is there another way to make sure this works out of the box on Windows?

**Comment by kmac** [comment]
Yes, I can make that off by default and enable it if debug is set.

However, the underlying issue is coming from the python requests library. According to this closed [issue #171](https://github.com/kennethreitz/requests-html/issues/171) this is a known issue, but the requests module is only supported on python 3.6. @SlimJimPoisson can you check if you are running python 3.5, and if so, is it feasible to upgrade to 3.6?

**Comment by SlimJimPoisson** [comment]
Actually, I am running 3.7. Let me know if you want me to test another version.

And as you both surmised the change worked perfectly. Sorry for the delay in responding. I have been spending my time getting up to speed on Python and the code base. I have encountered a number of other issues along the way, but I wanted to take more time to test the issues and possibly determine their cause before reporting anything. I do have a bunch of questions and possible issues to raise, but I didn't want to SPAM you with stupidity. Would you prefer that I open a new issue for each item, continue with a general discussion in this thread, or find another platform to exchange messages?

**Comment by suedunham** [comment]
I was able to get this to work on Win10 (python 3.7) by hard-coding utf-8 into line 91 of util.py, like
`with open(json_file, 'w', encoding='utf-8') as out:`

**Comment by kmac** [comment]
Thanks, I will make this change.
