### ISSUE TITLE
Cannot get mlbv to establish a connection

### ISSUE THREAD

**Issue by sdtallo** [kmac/mlbv#38]
Hey when I run mlbv -t tb --fetch i get something like this plus some more errors after handling this first exception

Traceback (most recent call last):
  File "C:\WinPython32-3.6.5.0Zero\python-3.6.5\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
  File "C:\WinPython32-3.6.5.0Zero\python-3.6.5\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
  File "C:\WinPython32-3.6.5.0Zero\python-3.6.5\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

My log file also says this when i run that command

2019-09-20 22:47:33,862 DEBUG MainThread mlbam.util Getting url=https://statsapi.mlb.com/api/v1/schedule?sportId=1&startDate=2019-09-20&endDate=2019-09-20&hydrate=broadcasts(all),game(content(all)),linescore,team ...
2019-09-20 22:47:33,862 DEBUG MainThread mlbam.util request_json: HTTP 'GET' request: https://statsapi.mlb.com/api/v1/schedule?sportId=1&startDate=2019-09-20&endDate=2019-09-20&hydrate=broadcasts(all),game(content(all)),linescore,team, headers:{'User-Agent': 'AppleCoreMedia/1.0.0.15B202 (iPhone; U; CPU OS 11_1_2 like Mac OS X; en_us)', 'Connection': 'close'}
2019-09-20 22:47:33,864 DEBUG MainThread urllib3.connectionpool Starting new HTTPS connection (1): statsapi.mlb.com:443
2019-09-20 22:47:34,408 DEBUG MainThread urllib3.connectionpool https://statsapi.mlb.com:443 "GET /api/v1/schedule?sportId=1&startDate=2019-09-20&endDate=2019-09-20&hydrate=broadcasts(all),game(content(all)),linescore,team HTTP/1.1" 200 None
2019-09-20 22:47:34,975 DEBUG MainThread urllib3.connectionpool Starting new HTTPS connection (1): web-secure.mlb.com:443

Just wondering why this isn't working is the service still working. Thanks and have a good day.

**Comment by mlb-fan** [comment]
Did you ever get it to work? I'm having the same error right now trying to download a couple games from the past season before my account expires. I haven't used the program since last year (it worked perfectly then) I don't know if I need to update anything.

**Comment by mlb-fan** [comment]
I was having the same problem, for me it was because I was using an outdated version of the program. I deleted any existing mlbv python directories then did a new install using pip and it's working again!

**Comment by kmac** [comment]
Closing this due to mlb-fan's comment. If it's still an issue then please reopen.
