### ISSUE TITLE
KeyError: 'mediaPlaybackId'

### ISSUE THREAD

**Issue by justpip** [kmac/mlbv#44]
I received a KeyError: 'mediaPlaybackId' when attempting to fetch the video. Command used: "mlbv --yes -t CHC --fetch --feed home". This command worked like a charm yesterday.

**Comment by SlimJimPoisson** [comment]
Same here. It appears to be a problem specifically with 2020-07-31. Other days do not cause this problem. Here is the trace log.

Running: mlbv.exe --date 2020-07-31 (though for today at least using --yesterday will cause the same problem).

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\mlbv.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\mlbv\mlbam\mlbv.py", line 203, in main
    game_day_tuple_list = gamedata_retriever.process_game_data(args.date, args.days)
  File "c:\program files\python37\lib\site-packages\mlbv\mlbam\mlbgamedata.py", line 216, in process_game_data
    game_records = self._get_games_by_date(game_date)
  File "c:\program files\python37\lib\site-packages\mlbv\mlbam\mlbgamedata.py", line 195, in _get_games_by_date
    game_rec['feed'][feedtype]['mediaPlaybackId'] = str(stream['mediaPlaybackId'])
KeyError: 'mediaPlaybackId'

**Comment by SlimJimPoisson** [comment]
I created a workaround that resolves this problem. If you edit the mlbgamedata.py file and comment out (add a "# " in front of) delete lines 190 through 198 it will work.

Line 190: elif media['title'] == 'Daily Recap':
Line 198: game_rec['feed'][feedtype]['playback_url'] = playback_item['url']

My guess is that this may remove the --Recap option so if you use that you will need to return the file to its original condition after you are finished with 2020-07-31.

**Comment by justpip** [comment]
Very helpful. Thank you.
