### ISSUE TITLE
Response 'forbidden' -> remove session file -> KeyError: 'assertion'

### ISSUE THREAD

**Issue by kmac** [kmac/mlbv#53]
Sometimes on the first game I watch I get a 'forbidden' response.

Sometimes the next try works, but if not, then I go and remove the ~/.config/mlbv/session file.

Then I get a KeyError: 'assertion' from mlbsession.py

Log snippet:

```
~> mlbv -t lad -i t1 --record
Could not load stream
{'errors': [{'code': 'forbidden'}]}
No game stream found for lad
~> rm ~/.config/mlbv/session 
rm: remove regular file '/home/htpc/.config/mlbv/session'? y
~> mlbv -t lad -i t1 --record
Traceback (most recent call last):
  File "/usr/bin/mlbv", line 33, in <module>
    sys.exit(load_entry_point('mlbv==0.0.18', 'console_scripts', 'mlbv')())
  File "/usr/lib/python3.9/site-packages/mlbv/mlbam/mlbv.py", line 318, in main
    return mlbstream.play_stream(game_rec, team_to_play, feedtype, args.date, args.fetch, args.from_start, args.inning)
  File "/usr/lib/python3.9/site-packages/mlbv/mlbam/mlbstream.py", line 97, in play_stream
    stream_url = mlb_session.lookup_stream_url(game_rec['game_pk'], media_playback_id)
  File "/usr/lib/python3.9/site-packages/mlbv/mlbam/mlbsession.py", line 323, in lookup_stream_url
    self._state["access_token"], self._state["token_expiry"], = self.get_access_token()
  File "/usr/lib/python3.9/site-packages/mlbv/mlbam/mlbsession.py", line 310, in get_access_token
    self.update_api_keys()
  File "/usr/lib/python3.9/site-packages/mlbv/mlbam/mlbsession.py", line 213, in update_api_keys
    DEVICES_ASSERTION = devices_response["assertion"]
KeyError: 'assertion'
```

And the next launch is successful.

My suspicion is that the session in the session file has expired (leading to the 'forbidden'). We shouldn't be caching it for so long. And then there's an error handling the new session that needs to taken care of.

**Comment by kmac** [comment]
Should be fixed in v0.0.19
