### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by macray76** [kmac/mlbv#62]
There seems to be an issue with the authorization credentials. I get the following error:

mlbv --team wsh --fetch --yesterday
Traceback (most recent call last):
  File "/home/macray76/.local/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/macray76/.local/bin/mlbv", line 8, in <module>
    sys.exit(main())
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/mlbv.py", line 318, in main
    return mlbstream.play_stream(game_rec, team_to_play, feedtype, args.date, args.fetch, args.from_start, args.inning)
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/mlbstream.py", line 98, in play_stream
    stream_url = mlb_session.lookup_stream_url(game_rec['game_pk'], media_playback_id)
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/mlbsession.py", line 273, in lookup_stream_url
    "Authorization": self.access_token,
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/common/session.py", line 125, in access_token
    self._refresh_access_token()
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/mlbsession.py", line 150, in _refresh_access_token
    self._state["OKTA_ACCESS_TOKEN"] = get_okta_token()
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/mlbsession.py", line 133, in get_okta_token
    "sessionToken": self.session_token,  # may trigger login
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/common/session.py", line 95, in session_token
    self.login()
  File "/home/macray76/.local/lib/python3.7/site-packages/mlbv/mlbam/mlbsession.py", line 86, in login
    authn_response = self.session.post(AUTHN_URL, json=authn_params).json()
  File "/home/macray76/.local/lib/python3.7/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value]
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <h1>Error 403 Forbidden</h1>
    <p>Forbidden</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-iad-kjyo7100079-IAD 1649416405 255336490</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by macray76** [comment]
Seems to have resolved itself except I now have a "Non-zero exit code from streamlink: 1" error.

Also showing [stream.hls][error] Failed to create decryptor: Unable to open URL:

**Comment by rcy** [comment]
I'm also seeing "Non-zero exit code from streamlink: 1" now
